### ISSUE TITLE
ICA output charts

### ISSUE THREAD

**Issue by stjep** [nipreps/mriqc#613]
Trying to understand the output that is generated by the `--ica` flag, but I'm having a hard time interpreting the plots next to each component.

The brainmaps look similar enough to what MELODIC generates that I'm (reasonably) okay with those.

It's unclear to me what the chart next to each component is indicating as there is no key or legend. I checked the docs and there is no mention of ICA other than highlighting that the flag exists. I also had a quick look in the code, which usually points out relevant papers, but couldn't find anything after a cursory look.

![ica plots](https://user-images.githubusercontent.com/3305421/28799019-bf739a32-7614-11e7-9e6c-4873e4b1f0f0.png)

**Comment by chrisfilo** [comment]
Indeed the documentations should be improved. Indeed we are running melodic to generate thos components. The graphic on the right is the unthresholded spatial map of the component (with a black overlay of the brain edge for reference). On the right in blue is the timecourse (it should be in seconds, but relies on correct RepetitionTime value in the sidecar JSON file (see BIDS spec) which seems to be off in your case - maybe you specified RT in msec instead of sec?). The plot in orange is the frequency decomposition (should be in Hz but also seems off in your case).

**Comment by chrisfilo** [comment]
One more point the spatial maps are maximum intensity projection (in other words "glass brains").

**Comment by stjep** [comment]
Thanks @chrisfilo. My TR was set to 2.0 (2000 ms), but I think my slice acquisition times are off, so I'm going to re-run it with that removed to see if the axis notation is fixed.

**Comment by chrisfilo** [comment]
Does your dataset pass the validator checks (
https://github.com/INCF/bids-validator) with no warnings?

**Comment by stjep** [comment]
I'm just testing this out on 1-2 functional files, but they do pass the BIDS validator. Anything else I could try to pin this down?

**Comment by chrisfilo** [comment]
Could you share the content of the relevant JSON file?

**Comment by chrisfilo** [comment]
I think it actually might be a bug in niworkflows https://github.com/poldracklab/niworkflows/issues/191

**Comment by stjep** [comment]
Ah, (somewhat) glad to hear it's not just me.

For completion sake, the contents of JSON file are below. It's the absolute bare minimum to be able to push this data through (I'm testing different sequences, so the data _should_ be clean):

```
{
    "RepetitionTime": 2.0,
    "TaskName": "rest",
    "Instruction": "Lie still and keep your eyes open"
}
```
