### ISSUE TITLE
requirements.txt does not exist

### ISSUE THREAD

**Issue by tashrifbillah** [nipreps/mriqc#830]
Refer to https://mriqc.readthedocs.io/en/stable/install.html#bare-metal-installation-only-python-3,

`requirements.txt` file does not exist. Maybe we need to update the documentation.

In the meantime, did you used to have the packages mentioned in [dockerfile](https://github.com/poldracklab/mriqc/blob/master/Dockerfile#L109) in `requirements.txt` ?

**Comment by tashrifbillah** [comment]
cc @sbouix @mglyons

**Comment by oesteban** [comment]
> Maybe we need to update the documentation.

Correct - could you send a PR?



> In the meantime, did you used to have the packages mentioned in [dockerfile](https://github.com/poldracklab/mriqc/blob/master/Dockerfile#L109) in `requirements.txt` ?

Those are indirect dependencies, which in principle, can be pinned to specific versions to give more reliability to the container images and save time when building them. Also, there's interest in pulling the packages from conda instead of pypi, as they usually come more optimized from the former.

**Comment by hfxcarl** [comment]
The main documentation on https://mriqc.readthedocs.io/en/latest/install.html points users to install python requirements from a file as shown here:
`pip install -r https://raw.githubusercontent.com/poldracklab/mriqc/master/requirements.txt`

But it appears the requirements are now located here:
> https://raw.githubusercontent.com/poldracklab/mriqc/master/docs/requirements.txt

**Comment by ZviBaratz** [comment]
@hfxcarl This issue seems to have been resolved in 206273826745847b41fc5c2b2c006a417c15a0bd, however, the documentation site seems to have been last built using commit b3a581627ef4c58f7e418fb184157aba19c85c09 from January 2019. 
@oesteban can this issue be closed? Also, should the documentation site be rebuilt?

**Comment by oesteban** [comment]
Okay, the documentation is now updated, and the requirements.txt removed (as we are moving towards PEP 518 installations).
