### ISSUE TITLE
Help highlighting a given entry in the group plot

### ISSUE THREAD

**Issue by pvelasco** [nipreps/mriqc#852]
Hi,

The users at our center would like to see how an image they have collected compares (in terms of iqms) to the images other groups collect in the same scanner using the same parameters.

I am able to query the web-api and download all the entries corresponding to our scanner. Then, I filter all the runs with identical set of relevant parameters (voxel size, bandwidth, etc.). Then, I would like to generate a report like the group reports you generate, but highlighting one of the datapoints (so that the user can identify the iqms for their particular run).

What I'm currently doing is I'm writing all the relevant entries into a `tsv` file, and using the call to `reports.group_html` to generate the report. Now, for each of the plots, is it possible to draw one of the points (e.g., the first, or the last one) in a different size or color?

Thanks!

**Comment by dfsp-spirit** [comment]
I don't know whether this is what you are looking for and this is definitely a hack, but since the output is a HTML report, you can select whatever element you want using jquery or whatever and change the style attributes.

You can also try it manually in your browser, e.g., in Firefox, use the DOM inspector (tools > Web Developer > Inspector) to manually select the element, then edit its style, hit enter to apply.

In the attached screenshot I have colored a single point red manually.

![overwrite](https://user-images.githubusercontent.com/1061893/89629727-9c7b9a80-d89e-11ea-98e7-5e6a806ff393.jpg)

**Comment by oesteban** [comment]
(follow-up in newly opened issue)
