### ISSUE TITLE
timepoints was wrong

### ISSUE THREAD

**Issue by Cynthia1229** [nipreps/mriqc#857]
Has anyone encountered the same problem as me? After processed with MRIQC 0.15.1, the size_t information in group_bold.tsv was wrong. The time points were inconsistent with the raw data and the preprocessed data. 

**code:** 
singularity run --cleanenv -B /seastor:/seastor $HOME/my_images/mriqc-0.15.1.simg \
$HOME/bids_dir $HOME/bids_dir/derivatives/mriqc \
participant --participant-label $subid \
-w $HOME/bids_dir/temporary_files \
--n_procs 12

singularity run --cleanenv -B /seastor:/seastor $HOME/my_images/mriqc-0.15.1.simg \
$HOME/bids_dir $HOME/bids_dir/derivatives/mriqc \
group

![image](https://user-images.githubusercontent.com/32211750/90857561-f90aa980-e3b6-11ea-9efd-1e555786afd3.png)
The correct number is 226.

I'm not sure if there was something wrong when I running the MRIQC...

**Comment by oesteban** [comment]
I'm not surprised that `size_t` is smaller than the original size of 226 for several of the subjects, as MRIQC extracts this information after identifying and removing nonsteady states in the beginning of the scan.

I'm more concerned about `sub-27` (I think that's the one) and `run-2`, as you got a length over 226. Could you check that this particular run is not actually 227 long?

I'm closing this issue as it is fairly old and, unless MRIQC is making out that extra volume for the given subject and run, this is completely expected behavior from MRIQC. Please reopen if the given subject and run is not 227-long.

Finally, let me remind everyone that MRIQC is not a preprocessing tool, and intermediate (internal) results of MRIQC should not be used for any purpose other than debugging the tool. In other words, the only outputs of MRIQC that are meant for secondary use are the visual reports and the JSON files containing quality metrics.
