### ISSUE TITLE
Using 3DFLAIR?

### ISSUE THREAD

**Issue by arthursw** [nipreps/mriqc#871]
Could MRIQC work with 3D FLAIR?
My goal is to classify my images, i.e. predict the quality labels (0=”accept”, 1=”reject”).

Or would it be possible to modify MRIQC to handle 3D FLAIR?

I guess that would mean modifying some Image Quality Metrics and / or the random-forests classifier ; yet I do not have much training data...

**Comment by arthursw** [comment]
Could I just use my FLAIR images as if they are T1w by renaming them?

**Comment by effigies** [comment]
In principle, MRIQC should be able to use FLAIR. If you're interested in trying to add it, I would suggest looking for "T2w" throughout the code base and seeing how far you get by duplicating what's done for it for FLAIR.

**Comment by fuentesdt** [comment]
Hi @arthursw did you ever try your renaming approach? I renamed Flair to T2w and seems to run. 

@effigies There is a step in the anatomy workflow that seems to download a T2w template ? https://templateflow.s3.amazonaws.com/tpl-MNI152NLin2009cAsym/tpl-MNI152NLin2009cAsym_res-02_T2w.nii.gz

Is there a FLAIR template that we should use for this? Otherwise, I plan to verify that the intermediate files in the anatomical workflow look OK to build confidence in the IQM output.

https://mriqc.readthedocs.io/en/latest/workflows.html#the-anatomical-workflow

$ find mriqc_wf/anatMRIQC/ | grep nii.gz$
mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz
mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/sstrip_orig_vol/sub-B001_ses-BRATS_T2w_conformed_calc.nii.gz
mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/inu_n4/sub-B001_ses-BRATS_T2w_conformed_bias.nii.gz
mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/inu_n4/sub-B001_ses-BRATS_T2w_conformed_corrected.nii.gz
mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/binarize/sub-B001_ses-BRATS_T2w_conformed_calc_mask.nii.gz
mriqc_wf/anatMRIQC/AFNISkullStripWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/skullstrip/sub-B001_ses-BRATS_T2w_conformed_corrected_skullstrip.nii.gz
mriqc_wf/anatMRIQC/SpatialNormalization/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz
mriqc_wf/anatMRIQC/ReportsWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz
mriqc_wf/anatMRIQC/HeadMaskWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz
mriqc_wf/anatMRIQC/HeadMaskWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/fsl_bet/sub-B001_ses-BRATS_T2w_conformed_corrected_brain_outskin_mask.nii.gz
mriqc_wf/anatMRIQC/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz
mriqc_wf/anatMRIQC/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/segmentation/segment_pve_2.nii.gz
mriqc_wf/anatMRIQC/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/segmentation/segment_pve_1.nii.gz
mriqc_wf/anatMRIQC/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/segmentation/segment_pve_0.nii.gz
mriqc_wf/anatMRIQC/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/segmentation/segment_seg.nii.gz
mriqc_wf/anatMRIQC/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/conform/sub-B001_ses-BRATS_T2w_conformed.nii.gz
mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz
mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/MNItpms2t1/mapflow/_MNItpms2t12/tpl-MNI152NLin2009cAsym_res-01_label-WM_probseg_trans.nii.gz
mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/MNItpms2t1/mapflow/_MNItpms2t10/tpl-MNI152NLin2009cAsym_res-01_label-CSF_probseg_trans.nii.gz
mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/MNItpms2t1/mapflow/_MNItpms2t11/tpl-MNI152NLin2009cAsym_res-01_label-GM_probseg_trans.nii.gz
mriqc_wf/anatMRIQC/ComputeIQMs/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/harmonize/sub-B001_ses-BRATS_T2w_conformed_corrected_harmonized.nii.gz
mriqc_wf/anatMRIQC/AirMaskWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz
mriqc_wf/anatMRIQC/AirMaskWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/ArtifactMask/sub-B001_ses-BRATS_T2w_conformed_air.nii.gz
mriqc_wf/anatMRIQC/AirMaskWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/ArtifactMask/sub-B001_ses-BRATS_T2w_conformed_art.nii.gz
mriqc_wf/anatMRIQC/AirMaskWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/ArtifactMask/sub-B001_ses-BRATS_T2w_conformed_hat.nii.gz
mriqc_wf/anatMRIQC/AirMaskWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/RotationMask/sub-B001_ses-BRATS_T2w_conformed_rotmask.nii.gz
mriqc_wf/anatMRIQC/AirMaskWorkflow/_in_file_..data..sub-B001..ses-BRATS..anat..sub-B001_ses-BRATS_T2w.nii.gz/invert_xfm/tpl-MNI152NLin2009cAsym_res-01_desc-head_mask_trans.nii.gz

**Comment by arthursw** [comment]
Hi @fuentesdt, yes I tried it, but I didn't get good results so we decided to go for manual QC.

**Comment by oesteban** [comment]
Extending MRIQC to FLAIR images would be an outstanding contribution, while not particularly terrible code-wise, in principle. However, we don't have enough hands to undertake it at the moment. Please feel invited to send a PR implementing this feature, we will review the code and get it merged gladly.
