### ISSUE TITLE
n_cpus flag not respecting max cpus

### ISSUE THREAD

**Issue by ulloaa** [nipreps/mriqc#931]
We have found that on our linux cluster the singularity image (pulled from docker) of mriqc does not respect the maximum number of CPUs passed with the flag n_cpus. Mriqc takes the maximum number of CPUs in an individual compute node regardless of the value of this flag. Any suggestions on how to handle this?

**Comment by mattcieslak** [comment]
We also have observed this using singularity on our cluster

**Comment by ulloaa** [comment]
So how do you deal with that @mattcieslak ? Something we observed is that the "high" hyperthreading occurs only in about 10% of a typical mriqc run. So I don't know if it makes sense to just request a large number of cpus within a run. Still, it would be useful to have an idea of why the n_cpus flag does not work. Or perhaps it is intended to work in a different way?

**Comment by effigies** [comment]
Seems to be a bug. From a quick glance, it's not clear why it's not being set correctly.

**Comment by psadil** [comment]
I think that I'm running into this same issue (running 21.0.0rc2 with Singularity). Looks like #961 will solve it. Until that's merged, perhaps a workaround could be to rely on `--use-plugin`. e.g.,

```
mriqc bids-root/ output-folder/ participant --use-plugin plugin.yml 
```
where `plugin.yml` contains

```
plugin : "MultiProc"
plugin_args:
 n_procs: 6
```
(note spaces) Running this at a local cluster, it seems like mriqc ends up restricted to the specified number of cores rather than the cores on the compute node, based on seeing
```
220116-21:27:07,534 nipype.workflow DEBUG:
[MultiProc] Starting (n_procs=6, [...]
```
in a run with debug-level verbosity.

**Comment by oesteban** [comment]
Thanks for the tip @psadil. #961 has been merged and this issue can be closed.
