### ISSUE TITLE
--start-idx and --stop-idx are ignored

### ISSUE THREAD

**Issue by psadil** [nipreps/mriqc#965]
Related to #321 

**What's happening**
I'm testing mriqc 21.0.0rc2 via Singularity on a dataset with a set number of dummy TRs. It's not entirely clear to me how these arguments are supposed to change processing, but it looks like the arguments `--start-idx` and `--stop-idx` are ignored. For example, a command that looks like

```
singularity run --cleanenv -B /inputs/rawdata:/bids:ro -B /outpus:/main /mriqc_21.0.0rc2.sif /bids \
/main/derivatives/mriqc participant -w /main/derivatives/work/mriqc \
--participant-label 0001 --session-id 01 \
--ica --verbose-reports --correct-slice-timing --start-idx 5 --stop-idx 1474 --no-sub \
--verbose-reports --fd_thres 0.9 --float --mem_gb 24 --use-plugin /main/code/config.yml -vvvv
```
gives a log that includes:

```
[...]
220117-09:59:02,157 nipype.workflow DEBUG:
	 [Node] drop_trs - setting input start_idx = <undefined>
220117-09:59:02,157 nipype.workflow DEBUG:
	 [Node] drop_trs - setting input stop_idx = <undefined>
[...]
```
And the `command.txt` in the working directory of the `drop_tr` node contains this line

```
3dcalc -a [<redacted input file>] -expr "a" -prefix [<redacted prefix>]
```
But from the [nipype function](https://github.com/nipy/nipype/blob/028913705642fcb58c549ac9f3b69ebafeb14043/nipype/interfaces/afni/utils.py#L492) I would have expected it to contain
```
3dcalc -a [<redacted input file>] -expr "a[5..1474]" -prefix [<redacted prefix>]
```

**Possible Cause**

These arguments could be used by the [`hmc` workflow](https://github.com/nipreps/mriqc/blob/21.0.0rc2/mriqc/workflows/functional.py#L643-L655), except that they aren't being passed to that workflow's inputnode ([e.g.](https://github.com/nipreps/mriqc/blob/21.0.0rc2/mriqc/workflows/functional.py#L99-L102)). 

I'm not sure about the intention with those parameters. There's also the ["non_steady_state_detector" node](https://github.com/nipreps/mriqc/blob/21.0.0rc2/mriqc/workflows/functional.py#L89-L91), but there doesn't seem to be any logic for choosing between the indexes given by the user and whatever is automatically flagged as a non-steady state TR.

**Comment by oesteban** [comment]
``--start-idx`` and ``--stop-idx`` are preprocessing options. I agree this is a bug, but it should not exist because the two options should not exist. MRIQC should not be used with preprocessing purposes.

**Comment by psadil** [comment]
I think that makes sense. Though, given the presence of a [non_steady_state_detector node](https://github.com/nipreps/mriqc/blob/112e4e97005a6ed709db269f550562760b18e0d2/mriqc/workflows/functional.py#L89-L91), I wonder whether you'd consider having an option like `--dummy-scans`. I would appreciate having the ability to exclude a few initial TRs, to simplify comparisons of metrics across datasets (e.g., AFNI's outlier ratio)

**Comment by oesteban** [comment]
Sure, that would not be a big deal - we can basically copy over from fMRIPrep.

**Comment by oesteban** [comment]
> I think that makes sense. Though, given the presence of a [non_steady_state_detector node](https://github.com/nipreps/mriqc/blob/112e4e97005a6ed709db269f550562760b18e0d2/mriqc/workflows/functional.py#L89-L91), I wonder whether you'd consider having an option like `--dummy-scans`. I would appreciate having the ability to exclude a few initial TRs, to simplify comparisons of metrics across datasets (e.g., AFNI's outlier ratio)

Upon some reflection, I'm leaning towards actually removing the option. The reason is that this option will have deleterious consequences: some of the metrics indeed will not be reported for the initial timesteps.

However, I acknowledge the problem. I believe the right solution is that downstream analyses (e.g., a classifier) should include the option in some way. For a fully automated classifier, you probably need something sophisticated that works without the original data, or force the user provide the parameter always. For other more lenient processes, some smart way of estimating it would be fine.

Another way of viewing this: if I train a classifier on a sample from my scanning center providing the dummy scans number always, and then, once I call it done, I stop providing the parameter, I would be biasing the classifier.

I agree this is an open issue, and perhaps we will need to report all the confounding timeseries rather than summary values.
